# zeroProxy逻辑配置，这里只是用来说明配置结构，最后配置数据会被持久化在DB中

# 配置的版本
config_name: 线上性能测试

# server user and password
user :  zerodb
password : zerodb

# only log the query that take more than slow_log_time ms
slow_log_time : 3000

# 如果推送proxy配置失败了，是否需要继续推送后续的proxy
push_when_fail: true

permit_multi_route: true

# 包含unreg「注销」和offline「下线」
stop_service:
    # 当某些数据源切换被拒多次后，又与keeper失联，是否需要「下线」
    offline_on_lost_keeper: true
    # 数据源切换被拒次数
    offline_swh_rejected_num: 3
    # 至少有两个Host连续被数据源切换失败后，让自己下线
    offline_down_host_num: 4
    # 下线后自己恢复
    # 连接上host后，proxy向keeper恢复心跳，keeper中标志proxy为"ready"
    offline_recover: true

switch:
    # 默认值为true
    need_vote: true
    # 只有当获得了 >= n% 的投票后才能数据源切换
    vote_approve_ratio: 50

    # 和target agent有关
    # 默认值为true
    need_load_check: true
    safe_load: 2

    # 与source agent和target agent都有关
    # need_binlog_check: false
    need_binlog_check: true
    #    mysql> show master status;
    #    +------------------+-----------+--------------+------------------+-------------------+
    #    | File             | Position  | Binlog_Do_DB | Binlog_Ignore_DB | Executed_Gtid_Set |
    #    +------------------+-----------+--------------+------------------+-------------------+
    #    | mysql-bin.000056 | 176224573 |              |                  |                   |
    #    +------------------+-----------+--------------+------------------+-------------------+
    safe_binlog_delay: 1000

host_groups:
-
    name : hostGroup1
    max_conn : 2560
    init_conn : 200
    user : zerodb
    password : zerodb@552208
    write : 10.12.1.66:3306,10.12.1.70:3306
    active_write: 0
#    read : 10.1.22.1:3306@3,10.1.22.1:3306@2

-
    name : hostGroup2
    # default max conns for mysql server
    max_conn : 2560
    init_conn : 200
    user : zerodb
    password : zerodb@552208
    write : 10.12.1.67:3306,10.12.1.71:3306
    active_write: 0
#    read : 10.1.22.2:3306@3,10.1.22.2:3306@2
-
    name : hostGroup3
    # default max conns for mysql server
    max_conn : 2560
    init_conn : 200
    user : zerodb
    password : zerodb@552208
    write : 10.12.1.68:3306,10.12.1.72:3306
    active_write: 0
#    read : 10.1.22.3:3306@3,10.1.22.3:3306@2
-
    name : hostGroup4
    # default max conns for mysql server
    max_conn : 2560
    init_conn : 200
    user : zerodb
    password : zerodb@552208
    write : 10.12.1.69:3306,10.12.1.73:3306
    active_write: 0
#    read : 10.1.22.4:3306@3,10.1.22.4:3306@2

schema_configs :
-
    name: zerodb
    nonsharding_host_group: hostGroup1
    sharding_host_groups: [hostGroup1,hostGroup2,hostGroup3,hostGroup4]
    rw_split: false
    schema_sharding: 128
    table_sharding: 1
    table_configs:
    -
        name: order_ins
        sharding_key: entity_id
        rule: int
    -
        name: ins_detail
        sharding_key: entity_id
        rule: int
    -
        name: benchyou0
        sharding_key: id
        rule: int
    -
        name: benchyou1
        sharding_key: id
        rule: int
    -
        name: benchyou2
        sharding_key: id
        rule: int
    -
        name: benchyou3
        sharding_key: id
        rule: int
    -
        name: benchyou4
        sharding_key: id
        rule: int
